name: Common Bun Workflow

on:
  workflow_call:
    inputs:
      bun-version:
        description: "Bun version used by the workflow"
        required: true
        type: string

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: ${{ inputs.bun-version }}
      - name: Install Dependencies
        run: bun install
      - name: Check Project
        run: bun run check
      - name: Check lint
        run: bun run lint

  #  test:
  #    runs-on: ubuntu-latest
  #    timeout-minutes: 10
  #    steps:
  #      - uses: actions/checkout@v4
  #      - uses: actions/setup-node@v4
  #        with:
  #          node-version: ${{ inputs.node-version }}
  #          cache: npm
  #      - name: Install Dependencies
  #        run: npm ci
  #      - name: Run test
  #        run: npm run test

  build:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: ${{ inputs.bun-version }}
      - name: Install Dependencies
        run: bun install
      - name: Build Project
        run: bun run build
